<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBiosTest\Log;

use MSBios\Log\ConfigProvider;
use PHPUnit\Framework\TestCase;

/**
 * Class ModuleTest
 * @package MSBiosTest\Log
 */
class ConfigProviderTest extends TestCase
{
    /** @var  ConfigProvider */
    protected $instance;

    /**
     *
     */
    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->instance = new ConfigProvider;
    }

    /**
     *
     */
    public function testInvokable()
    {
        /** @var ConfigProvider $instance */
        $instance = $this->instance;
        $this->assertInternalType('array', $instance());
    }

    /**
     *
     */
    public function testGetDependencyConfig()
    {
        /** @var ConfigProvider $instance */
        $instance = $this->instance;
        $this->assertInternalType('array', $instance->getDependencyConfig());
    }
}
